FROM prireg:5000/alpine-s6-overlay:3.11-1.21.8.0

ENV JAVA_ALPINE_VERSION 11.0.5_p10-r0
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk
ENV PATH $PATH:$JAVA_HOME/bin

RUN apk add --no-cache openjdk11-jre="$JAVA_ALPINE_VERSION"
